### ISSUE TITLE
Unpacking strings code appears to be dangerous

### ISSUE THREAD

**Issue by burillo-se** [xlab/vorbis-go#5]
https://github.com/xlab/vorbis-go/blob/master/vorbis/cgo_helpers.go#L1421

This helper will convert a Go string into a C char* pointer. However, it appears that sometimes these strings are not null-terminated (or at least not consistently so), so things blow up inside. We've just hit an issue where adding a Vorbis comment onto a stream read far beyond the comment string.

Seems like a copy/deref approach would be safer, if less performant?

**Comment by xlab** [comment]
Hi @burillo-se I'm glad you're doing good progress into using the generator and studying all the tradeoffs I made while developing it. There are two approaches to strings handling using c-for-go.

First is for advanced use cases and performance. That means you should add "\x00" to your strings as you would do in C and that is completely on your shoulders. This mode is for low-level bindings where a careful developer would use unsafe strings a few times.

For all other cases, the generator has SafeStrings directive in YAML
https://github.com/golang-ui/nuklear/blob/master/nk.yml#L8

It will automatically terminate all strings passed to C. But it would require copying and additional checks that may have performance impact.

As you know, all packages in vorbis-go were generated without this directive. I'm not sure if we need it here, let me know if it will significantly increase your productivity.

**Comment by burillo-se** [comment]
By now i should probably stop assuming that you didn't think of this before i did 🤣 

Is it possible to add SafeStrings to a single function? As far as i can tell, the add_comment function is the only one (OK, they're a few comment-related functions) which involves passing actual strings from Go to C library. This is not a encoder/decode-related API, so i wouldn't expect it to be called on a hotpath. Maybe enabling safe strings for this particular call would be a good idea?

Anyway, adding null-terminators to our strings fixed the issues, so the immediate problem is gone.

**Comment by xlab** [comment]
> Anyway, adding null-terminators to our strings fixed the issues

You can also create wrappers for this single functions in your code, if it makes calls to these in many places. By default, any extra convenience that is picked per-function or per-type basis should be put by hand. Either in the binding, or in a high-level package.

**Comment by xlab** [comment]
@burillo-se an example of good architecture is https://github.com/xlab/pocketsphinx-go where `pocketsphinx` package is the binding code, autogenerated from headers, but `sphinx` package is a convenient wrapper that exposes almost all pocketsphinx types and methods to users in a very safe fashion.
